apiVersion: v1
kind: Pod 
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  container:
    - name: voting-app 
      image: kodecloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80